apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: cards-against-formality-services
build:
  local: 
    concurrency: 0
  artifacts:
    - image: cache-mixin
      context: packages/cache-mixin
      docker:
        dockerfile: Dockerfile
    - image: db-mixin
      context: packages/db-mixin
      docker:
        dockerfile: Dockerfile
    - image: health-check
      context: packages/health-check
      docker:
        dockerfile: Dockerfile
    - image: nginx-gateway
      context: services/nginx
      docker:
        dockerfile: Dockerfile
    - image: admin-gateway-service
      context: services/admin-gateway-service
      docker:
        dockerfile: dev.Dockerfile
      requires:
        - image: cache-mixin
          alias: CACHE_MIXIN
        - image: health-check
          alias: HEALTH_CHECK
    - image: web-gateway-service
      context: services/web-gateway-service
      docker:
        dockerfile: dev.Dockerfile
      requires:
        - image: cache-mixin
          alias: CACHE_MIXIN
        - image: health-check
          alias: HEALTH_CHECK
    - image: websocket-gateway-service
      context: services/websocket-gateway-service
      docker:
        dockerfile: dev.Dockerfile
      requires:
        - image: cache-mixin
          alias: CACHE_MIXIN
        - image: health-check
          alias: HEALTH_CHECK
    - image: cards-service
      context: services/cards-service
      docker:
        dockerfile: dev.Dockerfile
      requires:
        - image: cache-mixin
          alias: CACHE_MIXIN
        - image: db-mixin
          alias: DB_MIXIN
        - image: health-check
          alias: HEALTH_CHECK
    - image: decks-service
      context: services/decks-service
      docker:
        dockerfile: dev.Dockerfile
      requires:
        - image: cache-mixin
          alias: CACHE_MIXIN
        - image: db-mixin
          alias: DB_MIXIN
        - image: health-check
          alias: HEALTH_CHECK
    - image: clients-service
      context: services/clients-service
      docker:
        dockerfile: dev.Dockerfile
      requires:
        - image: cache-mixin
          alias: CACHE_MIXIN
        - image: db-mixin
          alias: DB_MIXIN
        - image: health-check
          alias: HEALTH_CHECK
    - image: rooms-service
      context: services/rooms-service
      docker:
        dockerfile: dev.Dockerfile
      requires:
        - image: cache-mixin
          alias: CACHE_MIXIN
        - image: db-mixin
          alias: DB_MIXIN
        - image: health-check
          alias: HEALTH_CHECK
    - image: games-service
      context: services/games-service
      docker:
        dockerfile: dev.Dockerfile
      requires:
        - image: cache-mixin
          alias: CACHE_MIXIN
        - image: db-mixin
          alias: DB_MIXIN
        - image: health-check
          alias: HEALTH_CHECK
deploy:
  kubectl:
    manifests:
      - services/nginx/k8s-svc.dev.yaml
      - services/nginx/k8s-pod.yaml
      - config/secret.yaml
      - config/base-config.yaml
      - services/admin-gateway-service/k8s-pod.yaml
      - services/admin-gateway-service/k8s-svc.yaml
      - services/web-gateway-service/k8s-pod.yaml
      - services/web-gateway-service/k8s-svc.yaml
      - services/websocket-gateway-service/k8s-pod.yaml
      - services/websocket-gateway-service/k8s-svc.yaml
      - services/cards-service/k8s-pod.yaml
      - services/decks-service/k8s-pod.yaml
      - services/clients-service/k8s-pod.yaml
      - services/rooms-service/k8s-pod.yaml
      - services/games-service/k8s-pod.yaml
  helm:
    releases:
      - name: nats
        chartPath: bitnami-full-index/nats
        version: 6.1.1
        remote: true
        setValues:
          auth.enabled: false
      - name: redis
        chartPath: bitnami-full-index/redis
        version: 12.6.2
        remote: true
        setValues:
          usePassword: false
          auth.enabled: false
          master.persistence.enabled: false
          slave.persistence.enabled: false
      - name: cards-mongo
        chartPath: bitnami-full-index/mongodb
        version: 10.4.1
        remote: true
        setValues: 
          usePassword: false
          auth.enabled: false
      - name: clients-mongo
        chartPath: bitnami-full-index/mongodb
        version: 10.4.1
        remote: true
        setValues: 
          persistence.enabled: false
          usePassword: false
          auth.enabled: false
      - name: decks-mongo
        chartPath: bitnami-full-index/mongodb
        version: 10.4.1
        remote: true
        setValues: 
          usePassword: false
          auth.enabled: false
      - name: games-mongo
        chartPath: bitnami-full-index/mongodb
        version: 10.4.1
        remote: true
        setValues: 
          persistence.enabled: false
          usePassword: false
          auth.enabled: false
      - name: rooms-mongo
        chartPath: bitnami-full-index/mongodb
        version: 10.4.1
        remote: true
        setValues: 
          persistence.enabled: false
          usePassword: false
          auth.enabled: false
profiles:
  - name: gcb
    patches:
      - op: replace
        path: /build/artifacts/4/docker/dockerfile
        value: Dockerfile
      - op: replace
        path: /build/artifacts/5/docker/dockerfile
        value: Dockerfile
      - op: replace
        path: /build/artifacts/6/docker/dockerfile
        value: Dockerfile
      - op: replace
        path: /build/artifacts/7/docker/dockerfile
        value: Dockerfile
      - op: replace
        path: /build/artifacts/8/docker/dockerfile
        value: Dockerfile
      - op: replace
        path: /build/artifacts/9/docker/dockerfile
        value: Dockerfile
      - op: replace
        path: /build/artifacts/10/docker/dockerfile
        value: Dockerfile
      - op: replace
        path: /build/artifacts/11/docker/dockerfile
        value: Dockerfile
    deploy:
      kubectl:
        manifests:
          - config/managed-cert.yaml
          - config/load-balancer-backend-config.yaml
          - config/ingress.yaml

          - services/nginx/k8s-svc.yaml
          - services/nginx/k8s-pod.yaml
          - config/secret.yaml
          - config/base-config.yaml
          - services/admin-gateway-service/k8s-pod.yaml
          - services/admin-gateway-service/k8s-svc.yaml
          - services/web-gateway-service/k8s-pod.yaml
          - services/web-gateway-service/k8s-svc.yaml
          - services/websocket-gateway-service/k8s-pod.yaml
          - services/websocket-gateway-service/k8s-svc.yaml
          - services/cards-service/k8s-pod.yaml
          - services/decks-service/k8s-pod.yaml
          - services/clients-service/k8s-pod.yaml
          - services/rooms-service/k8s-pod.yaml
          - services/games-service/k8s-pod.yaml
