apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: websocket-gateway-service
  name: websocket-gateway-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-gateway-service
  template:
    metadata:
      labels:
        app: websocket-gateway-service
    spec:
      containers:
        - name: websocket-gateway-service
          image: websocket-gateway-service
          livenessProbe:
            httpGet:
              path: /live
              port: 3001
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
          envFrom:
            - configMapRef:
                name: base-config
          env:
            - name: PORT
              value: "80"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-auth
                  key: jwtSecret
          ports:
            - containerPort: 80
      restartPolicy: Always
