apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: games-service
  name: games-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: games-service
  template:
    metadata:
      labels:
        app: games-service
    spec:
      containers:
        - name: games-service
          image: games-service
          livenessProbe:
            httpGet:
              path: /live
              port: 3001
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
          envFrom:
            - configMapRef:
                name: base-config
          env:
            - name: PORT
              value: "80"
            - name: MONGO_URI
              value: mongodb://games-mongo-mongodb.default.svc.cluster.local:27017
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 140m
      restartPolicy: Always
