apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-gateway-service
  name: admin-gateway-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-gateway-service
  template:
    metadata:
      labels:
        app: admin-gateway-service
    spec:
      containers:
        - name: admin-gateway-service
          image: admin-gateway-service
          livenessProbe:
            httpGet:
              path: /live
              port: 3001
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
          envFrom:
            - configMapRef:
                name: base-config
          env:
            - name: PORT
              value: "80"
            - name: REQUESTS_PER_MINUTE
              value: "100000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-auth
                  key: jwtSecret
          resources:
            requests:
              cpu: 40m
            limits:
              cpu: 70m
          ports:
            - containerPort: 80
      restartPolicy: Always
